parameters:
    glooby.debug.dumper.enable: false
    glooby.debug.dumpdir: "%kernel.root_dir%/logs/%kernel.environment%"

services:
    glooby.debug.dumper:
        class: Glooby\Debug\Dumper\Dumper
        calls:
            - [setEnabled,   ['%glooby.debug.dumper.enable%']]
            - [setFormatter, ['@glooby.debug.formatter']]
            - [setWriter,    ['@glooby.debug.writer']]

    glooby.debug.formatter:
        class: Glooby\Debug\Formatter\Formatter
        calls:
            - [setFormatterFactory, ['@glooby.debug.formatter.factory']]

    glooby.debug.formatter.factory:
        class: Glooby\Debug\Formatter\FormatterFactory

    glooby.debug.writer:
        class: Glooby\Debug\Writer\FileWriter
        calls:
            - [setDirectory, [ '%glooby.debug.dumpdir%' ]]
